alipay:
  appId: 2016091200495262
  #服务器异步通知页面路径
  notify_url: http://test.gongwk.com/notify/alipay
  #页面跳转同步通知页面路径
  return_url: http://test.gongwk.com/paySuccess.html
  #请求网关地址
  URL: https://openapi.alipaydev.com/gateway.do
  publicKey:
  privateKey:
  logPath: